;; This code was automatically generated by the 'metav' library.
(ns scenari.meta)

(def module-name "clornichon")
(def path ".")
(def version "0.1.2")
(def tag "v0.1.2")
(def generated-at "2026-09-27T08:53:06Z")
