;; This code was automatically generated by the 'metav' library.
(ns scenari.meta)

(def module-name "clornichon")
(def path ".")
(def version "0.1.10")
(def tag "v0.1.10")
(def generated-at "2026-09-27T17:25:31Z")
