;; This code was automatically generated by the 'metav' library.
(ns scenari.meta)

(def module-name "clornichon")
(def path ".")
(def version "0.1.11")
(def tag "v0.1.11")
(def generated-at "2026-09-27T20:17:36Z")
